# Generated by Django 4.1.3 on 2022-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
